# FORK: URL routes for fork-only endpoints, appended to urls.py's
# urlpatterns with a single line to keep the upstream file mergeable.
from django.urls import re_path

from . import (
    cinetrack_bootstrap_views,
    fork_views,
    fork_views_discover,
    fork_views_integrations,
    fork_views_lists,
    fork_views_metadata,
    fork_views_music,
    fork_views_playback,
    fork_views_podcast,
    fork_views_progress_changes,
    fork_views_scrobble,
    fork_views_statistics,
    fork_views_tracking,
    fork_views_users,
    fork_views_watched_state,
)

urlpatterns = [
    re_path(
        r"^cinetrack/bootstrap/movies/ensure/?$",
        cinetrack_bootstrap_views.CineTrackBootstrapMoviesEnsureView.as_view(),
        name="api_cinetrack_bootstrap_movies_ensure",
    ),
    re_path(
        r"^cinetrack/bootstrap/shows/ensure/?$",
        cinetrack_bootstrap_views.CineTrackBootstrapShowsEnsureView.as_view(),
        name="api_cinetrack_bootstrap_shows_ensure",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/(?P<season_number>\d+)/episodes/(?P<episode_number>\d+)/watch/?$",
        fork_views_tracking.MediaEpisodeWatchView.as_view(),
        name="api_media_episode_watch",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/(?P<season_number>\d+)/episodes/(?P<episode_number>\d+)/drop/?$",
        fork_views_tracking.MediaEpisodeDropView.as_view(),
        name="api_media_episode_drop",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/watch/?$",
        fork_views_tracking.MediaMovieWatchView.as_view(),
        name="api_media_movie_watch",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/(?P<season_number>\d+)/episodes/(?P<episode_number>\d+)/score/?$",
        fork_views_metadata.MediaEpisodeScoreView.as_view(),
        name="api_media_episode_score",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/provider-preference/?$",
        fork_views_metadata.MediaProviderPreferenceView.as_view(),
        name="api_media_provider_preference",
    ),
    re_path(
        r"^metadata/items/(?P<item_id>\d+)/image/?$",
        fork_views_metadata.ItemImageView.as_view(),
        name="api_item_image",
    ),
    re_path(
        r"^metadata/items/(?P<item_id>\d+)/?$",
        fork_views_metadata.ItemMetadataView.as_view(),
        name="api_item_metadata",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/episodes/bulk/?$",
        fork_views_tracking.MediaEpisodeBulkView.as_view(),
        name="api_media_episode_bulk",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/episodes/ensure/?$",
        cinetrack_bootstrap_views.MediaEpisodeEnsureView.as_view(),
        name="api_media_episode_ensure",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/tags/?$",
        fork_views_tracking.MediaTagsView.as_view(),
        name="api_media_tags",
    ),
    re_path(
        r"^history/?$",
        fork_views_tracking.HistoryView.as_view(),
        name="api_history",
    ),
    re_path(
        r"^history/(?P<media_type>[^/]+)/(?P<history_id>[^/]+)/?$",
        fork_views_tracking.HistoryRecordView.as_view(),
        name="api_history_record",
    ),
    re_path(
        r"^tags/?$",
        fork_views_tracking.TagsView.as_view(),
        name="api_tags",
    ),
    re_path(
        r"^tags/(?P<tag_id>\d+)/?$",
        fork_views_tracking.TagDetailView.as_view(),
        name="api_tag_detail",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/progress/?$",
        fork_views.MediaProgressView.as_view(),
        name="api_media_progress",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/(?P<season_number>\d+)/progress/?$",
        fork_views.MediaProgressView.as_view(),
        name="api_media_season_progress",
    ),
    re_path(
        r"^collection/?$",
        fork_views.CollectionView.as_view(),
        name="api_collection",
    ),
    re_path(
        r"^collection/(?P<entry_id>\d+)/?$",
        fork_views.CollectionEntryView.as_view(),
        name="api_collection_entry",
    ),
    re_path(
        r"^tasks/(?P<task_id>[\w-]+)/?$",
        fork_views.TaskStatusView.as_view(),
        name="api_task_status",
    ),
    re_path(
        r"^music/artists/?$",
        fork_views_music.MusicArtistsView.as_view(),
        name="api_music_artists",
    ),
    re_path(
        r"^music/artists/(?P<artist_id>\d+)/?$",
        fork_views_music.MusicArtistDetailView.as_view(),
        name="api_music_artist_detail",
    ),
    re_path(
        r"^music/artists/(?P<artist_id>\d+)/sync-discography/?$",
        fork_views_music.MusicArtistSyncView.as_view(),
        name="api_music_artist_sync",
    ),
    re_path(
        r"^music/artists/(?P<artist_id>\d+)/plays/?$",
        fork_views_music.MusicArtistPlaysView.as_view(),
        name="api_music_artist_plays",
    ),
    re_path(
        r"^music/albums/?$",
        fork_views_music.MusicAlbumsView.as_view(),
        name="api_music_albums",
    ),
    re_path(
        r"^music/albums/(?P<album_id>\d+)/?$",
        fork_views_music.MusicAlbumDetailView.as_view(),
        name="api_music_album_detail",
    ),
    re_path(
        r"^music/albums/(?P<album_id>\d+)/tracks/?$",
        fork_views_music.MusicAlbumTracksView.as_view(),
        name="api_music_album_tracks",
    ),
    re_path(
        r"^music/albums/(?P<album_id>\d+)/plays/?$",
        fork_views_music.MusicAlbumPlaysView.as_view(),
        name="api_music_album_plays",
    ),
    re_path(
        r"^music/songs/plays/?$",
        fork_views_music.MusicSongPlayView.as_view(),
        name="api_music_song_play",
    ),
    re_path(
        r"^music/tracks/(?P<music_id>\d+)/score/?$",
        fork_views_music.MusicTrackScoreView.as_view(),
        name="api_music_track_score",
    ),
    re_path(
        r"^music/bulk-plays/?$",
        fork_views_music.MusicBulkPlaysView.as_view(),
        name="api_music_bulk_plays",
    ),
    re_path(
        r"^podcasts/shows/?$",
        fork_views_podcast.PodcastShowsView.as_view(),
        name="api_podcast_shows",
    ),
    re_path(
        r"^podcasts/lookup/(?P<itunes_id>\d+)/?$",
        fork_views_podcast.PodcastLookupView.as_view(),
        name="api_podcast_lookup",
    ),
    re_path(
        r"^podcasts/shows/(?P<show_id>\d+)/?$",
        fork_views_podcast.PodcastShowDetailView.as_view(),
        name="api_podcast_show_detail",
    ),
    re_path(
        r"^podcasts/shows/(?P<show_id>\d+)/episodes/?$",
        fork_views_podcast.PodcastShowEpisodesView.as_view(),
        name="api_podcast_show_episodes",
    ),
    re_path(
        r"^podcasts/shows/(?P<show_id>\d+)/mark-all-played/?$",
        fork_views_podcast.PodcastMarkAllPlayedView.as_view(),
        name="api_podcast_mark_all_played",
    ),
    re_path(
        r"^podcasts/episodes/plays/?$",
        fork_views_podcast.PodcastEpisodePlayView.as_view(),
        name="api_podcast_episode_play",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/smart-rules/?$",
        fork_views_lists.ListSmartRulesView.as_view(),
        name="api_list_smart_rules",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/smart-sync/?$",
        fork_views_lists.ListSmartSyncView.as_view(),
        name="api_list_smart_sync",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/collaborators/?$",
        fork_views_lists.ListCollaboratorsView.as_view(),
        name="api_list_collaborators",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/items/reorder/?$",
        fork_views_lists.ListItemsReorderView.as_view(),
        name="api_list_items_reorder",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/items/order/?$",
        fork_views_lists.ListItemsOrderView.as_view(),
        name="api_list_items_order",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/recommendations/?$",
        fork_views_lists.ListRecommendationsView.as_view(),
        name="api_list_recommendations",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/recommendations/(?P<recommendation_id>\d+)/(?P<decision>approve|deny)/?$",
        fork_views_lists.ListRecommendationDecisionView.as_view(),
        name="api_list_recommendation_decision",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/activity/?$",
        fork_views_lists.ListActivityView.as_view(),
        name="api_list_activity",
    ),
    re_path(
        r"^collection/status/(?P<item_id>\d+)/?$",
        fork_views_discover.CollectionStatusView.as_view(),
        name="api_collection_status",
    ),
    re_path(
        r"^collection/seasons/(?P<season_item_id>\d+)/?$",
        fork_views_discover.CollectionSeasonView.as_view(),
        name="api_collection_season",
    ),
    re_path(
        r"^discover/?$",
        fork_views_discover.DiscoverRowsView.as_view(),
        name="api_discover",
    ),
    re_path(
        r"^discover/refresh/?$",
        fork_views_discover.DiscoverRefreshView.as_view(),
        name="api_discover_refresh",
    ),
    re_path(
        r"^discover/hidden/?$",
        fork_views_discover.DiscoverHiddenView.as_view(),
        name="api_discover_hidden",
    ),
    re_path(
        r"^home/?$",
        fork_views_discover.HomeView.as_view(),
        name="api_home",
    ),
    re_path(
        r"^user/preferences/?$",
        fork_views_users.UserPreferencesView.as_view(),
        name="api_user_preferences",
    ),
    re_path(
        r"^user/sidebar/?$",
        fork_views_users.UserSidebarView.as_view(),
        name="api_user_sidebar",
    ),
    re_path(
        r"^user/notifications/?$",
        fork_views_users.UserNotificationsView.as_view(),
        name="api_user_notifications",
    ),
    re_path(
        r"^user/notifications/exclusions/?$",
        fork_views_users.UserNotificationExclusionsView.as_view(),
        name="api_user_notification_exclusions",
    ),
    re_path(
        r"^user/notifications/test/?$",
        fork_views_users.UserNotificationTestView.as_view(),
        name="api_user_notification_test",
    ),
    re_path(
        r"^user/token/regenerate/?$",
        fork_views_users.UserTokenRegenerateView.as_view(),
        name="api_user_token_regenerate",
    ),
    re_path(
        r"^imports/activity/?$",
        fork_views_integrations.ImportActivityView.as_view(),
        name="api_imports_activity",
    ),
    re_path(
        r"^imports/(?P<service>[\w-]+)/?$",
        fork_views_integrations.ImportDispatchView.as_view(),
        name="api_import_dispatch",
    ),
    re_path(
        r"^export/csv/?$",
        fork_views_integrations.ExportCsvView.as_view(),
        name="api_export_csv",
    ),
    re_path(
        r"^export/template/?$",
        fork_views_integrations.ExportTemplateView.as_view(),
        name="api_export_template",
    ),
    re_path(
        r"^playback/progress/?$",
        fork_views_playback.PlaybackProgressView.as_view(),
        name="api_playback_progress",
    ),
    re_path(
        r"^playback/now-playing/?$",
        fork_views_playback.NowPlayingView.as_view(),
        name="api_playback_now_playing",
    ),
    re_path(
        r"^scrobble/?$",
        fork_views_scrobble.ScrobbleView.as_view(),
        name="api_scrobble",
    ),
    re_path(
        r"^statistics/overview/?$",
        fork_views_statistics.StatisticsOverviewView.as_view(),
        name="api_statistics_overview",
    ),
    re_path(
        r"^statistics/refresh/?$",
        fork_views_statistics.StatisticsRefreshView.as_view(),
        name="api_statistics_refresh",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>[^/]+)/"
        r"watched-state/?$",
        fork_views_watched_state.WatchedStateView.as_view(),
        name="api_watched_state",
    ),
    re_path(
        r"^sync/changes/?$",
        fork_views_watched_state.WatchedStateChangeFeedView.as_view(),
        name="api_sync_changes",
    ),
    re_path(
        r"^sync/progress-changes/?$",
        fork_views_progress_changes.ProgressChangeFeedView.as_view(),
        name="api_sync_progress_changes",
    ),
    re_path(
        r"^sync/connections/?$",
        fork_views_watched_state.SyncConnectionsView.as_view(),
        name="api_sync_connections",
    ),
    re_path(
        r"^sync/conflicts/?$",
        fork_views_watched_state.SyncConflictsView.as_view(),
        name="api_sync_conflicts",
    ),
    re_path(
        r"^sync/conflicts/(?P<conflict_id>\d+)/resolve/?$",
        fork_views_watched_state.SyncConflictResolveView.as_view(),
        name="api_sync_conflict_resolve",
    ),
]
